import "./globals.css";
import LanguageContext from "../contexts/LanguageContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LanguageContext>{children}</LanguageContext>
      </body>
    </html>
  );
}
